version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 082972943693.dkr.ecr.ap-south-1.amazonaws.com"

  build:
    commands:
      - echo "Build started on `date`"
      - echo "1. Generating JAR file..."
      - "mvn clean package"
      
      - echo "2. Building Docker Image..."
      - "docker build -t uday-ecr ."
      
      - "docker tag uday-ecr:latest 082972943693.dkr.ecr.ap-south-1.amazonaws.com/uday-ecr:latest"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "3. Pushing Docker Image to ECR..."
      - "docker push 082972943693.dkr.ecr.ap-south-1.amazonaws.com/uday-ecr:latest"
      - echo "Success! Image Successfully Pushed."

artifacts:
  files:
    - "target/*.jar"
