version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Java 17 environment
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # Docker ko AWS ECR se connect karna
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <YOUR_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Java project...
      - mvn clean package
      
      - echo Building the Docker image...
      - docker build -t my-demo-app-repo .
      - docker tag my-demo-app-repo:latest <YOUR_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/my-demo-app-repo:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push <YOUR_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/my-demo-app-repo:latest
